export const ADD_DATA_WAEATHER = 'ADD_DATA_WAEATHER';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_CURRENT_NOW = 'SET_CURRENT_NOW';
export const SET_GPS_PERISSION = 'SET_GPS_PERISSION';
export const SET_LOCATION_NAME = 'SET_LOCATION_NAME';
export const SET_LANG = 'SET_LANG';
export const SET_POSITION = 'SET_POSITION';
export const SET_FULL_STATE = 'SET_FULL_STATE';
